@echo off
@echo Installing mineflayer....
npm install mineflayer 
@echo Installing axios....
npm install axios
@echo Installing fs....
npm install fs
@echo Installing mineflayer-pathfinder.....
npm install mineflayer-pathfinder
@echo Installing express.....
npm install express
@echo Installing ws....
npm install ws
@echo Installing prismarine viewer....
npm install prismarine-viewer
pause
